version: "3"
services:
  credential_digger:
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        - path_model=$path_model
        - snippet_model=$snippet_model
    container_name: credential_digger_sqlite
    restart: always
    env_file:
      - ./.env
    ports:
      - "5000:5000"
