version: "3"
services:
  credential_digger:
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        - SSL_certificate=$SSL_certificate
        - SSL_private_key=$SSL_private_key
    container_name: credential_digger_sqlite
    image: credential-digger_sqlite
    restart: always
    env_file:
      - ./.env
    ports:
      - "5000:5000"
